=== Fredericodgv/FlipNflop/Assets/Schema/level_configuration.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://JEDCIRCUITOS/Assets/Schema/level_configuration.schema.json",
    "title": "Esquema de Nível de Jogo",
    "description": "Define a estrutura de um arquivo JSON de configuração de nível.",
    "type": "object",
    "properties": {
        "levelName": {
            "type": "string",
            "description": "O nome descritivo do nível (formato: 'level_n')."
        },
        "levelDescription": {
            "type": "string",
            "description": "Descrição detalhada do nível."
        },
        "levelID": {
            "type": "string",
            "description": "ID para identificação de ordenação de fases."
        },
        "levelOrder": {
          	"type": "integer",
            "description": "Define um número inteiro de encaixe para a ordenação de disposição de fases."
        },
       	"ffType": {
          	"type": "string",
            "enum": ["JK", "SR", "T", "D"],
            "description": "Define qual o tipo do flip flop desta fase"
        },
        "clockCicles": {
            "type": "integer",
            "minimum": 1,
            "description": "Quantidade de ciclos de clock na fase."
        },
        "activeClockEdge": {
            "type": "string",
            "enum": ["rising", "falling"],
            "description": "Define se o sinal responde à borda de subida ou descida."
        },
        "jSignal": {
            "type": "string",
            "pattern": "^[01 ]+$",
            "description": "Sequência binária para o J (sequência de 1s e 0s)."
        },
        "kSignal": {
            "type": "string",
            "pattern": "^[01 ]+$",
            "description": "Sequência binária para o K (sequência de 1s e 0s)."
        },
        "presetSignal": {
            "type": "string",
            "pattern": "^[01 ]+$",
            "description": "Sequência binária para sinal assíncrono Preset (sequência de 1s e 0s)."
        },
        "clearSignal": {
          	"type": "string",
            "pattern": "^[01 ]+$",
            "description": "Sequência binária para sinal assíncrono Clear (sequência de 1s e 0s)."
        },
        "asyncActive": {
            "type": "string",
            "enum": ["high", "low"],
            "description": "Define se sinais assíncronos estão ativos em 1 ou em 0."
        },
        "floor": {
            "type": "string",
            "pattern": "^[01 ]+$",
            "description": "Representação binária do chão"
        },
        "ceiling": {
            "type": "string",
            "pattern": "^[01 ]+$",
            "description": "Representação binária do teto"
        },
        "obstacles": {
            "type": "array",
            "description": "Lista de configurações para geração de diferentes obstáculos.",
            "items": {
                "type": "object",
                "properties": {
                    "obstacleName": {
                        "type": "string",
                        "description": "Nome/ID do obstáculo a ser gerado.",
                        "enum": [
                            "Rock",
                            "Mace",
                            "Button",
                            "Wall",
                            "SpikeTrap",
                            "MovingPlatform"
                        ]
                    },
                    "startX": { "type": "number" },
                    "startY": { "type": "number" },
                    "speed": { "type": "number"},
                    "horizontalDistance": { "type": "number" },
                    "verticalDistance": { "type": "number" },
                    "starterCorner": { "type": "string" },
                    "clockwise": { "type": "boolean" }
                },
                "required": [
                    "obstacleName",
                    "startX",
                    "startY"
                ],
                "additionalProperties": false
            }
        }
    },
    "required": [
        "levelName",
      	"levelDescription",
		"ffType",
        "clockCicles",
        "activeClockEdge",
        "floor",
        "ceiling",
        "obstacles"
    ],
    "dependencies": {
    	"presetSignal": ["asyncActive"],
        "clearSignal": ["asyncActive"]
    },
    "allOf": [
      {
      	"if": {
          "properties": { "ffType": { "const": "JK" } }
        },
        "then": {
          "required": ["jSignal", "kSignal"]
        }
      },
      {
        "if": { "required": ["asyncActive"] },
        "then": {
          "anyOf": [
            { "required": ["presetSignal"] },
            { "required": ["clearSignal"] }
          ]
        }
      }
    ],
    "additionalProperties": false
}

=== Fredericodgv/FlipNflop/Assets/Resources/Levels/eighth_level.json
{
    "levelName": "eighth_level",
    "levelDescription": "Fase fácil com reunião de todos os conceitos introduzidos",
    "levelID": "97951360",
    "levelOrder": 80,
    "ffType": "JK",
    "clockCicles": 9,
    "activeClockEdge": "rising",  
    "jSignal": "000011 111000 000001 111100 000111 111000 000111 100111 100000 000000",
    "kSignal": "000000 001111 110011 111000 000000 110001 110011 111001 111100 000000",
    "presetSignal": "111111 111111 111111 111111 111111 111111 110000 001111 111111 111111",
    "clearSignal": "111111 111111 111111 111111 111111 100011 111111 111111 110011 111111",
    "asyncActive": "low",
    "ceiling": "111111 110011 100011 111111 110001 111111 111001 111111 111100 011111",
    "floor": "111111 110011 100011 111111 110001 111111 111001 111111 111100 011111",
    "obstacles": [
        {
            "obstacleName": "Mace",
            "startX": 20,
            "startY": 1,
            "speed": 0,
            "horizontalDistance": 0,
            "verticalDistance": 0,
            "starterCorner": "bottom-left",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 26,
            "startY": 3,
            "speed": 0,
            "horizontalDistance": 0,
            "verticalDistance": 0,
            "starterCorner": "bottom-right",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 33,
            "startY": 1,
            "speed": 2,
            "horizontalDistance": 1,
            "verticalDistance": 4,
            "starterCorner": "bottom-left",
            "clockwise": false
        },
        {
            "obstacleName": "Mace",
            "startX": 45,
            "startY": 3,
            "speed": 1,
            "horizontalDistance": 5,
            "verticalDistance": 0,
            "starterCorner": "bottom-left",
            "clockwise": true
        }
    ]
}

=== Fredericodgv/FlipNflop/Assets/Resources/Levels/seventh_level.json
{
    "levelName": "seventh_level",
    "levelDescription": "Implementa obstáculos mace com movimento vertical",
    "levelID": "76278262",
    "levelOrder": 60,
    "ffType": "JK",
    "clockCicles": 8,
    "activeClockEdge": "rising",  
    "jSignal": "000011 111000 000011 100001 111001 111000 001111 000000 001111",
    "kSignal": "001111 110000 000001 111000 011111 100001 111100 001110 000000",
    "clearSignal": "111111 111000 011111 110000 011111 111111 100011 111110 000000",
    "asyncActive": "low", 
    "ceiling": "111111 111111 111111 111111 111111 110001 111111 111111 111111 111111",
    "floor": "111111 111111 110001 111001 111111 111111 111111 111111 111111 111111",
    "obstacles": [
        {
            "obstacleName": "Mace",
            "startX": 4,
            "startY": 1,
            "speed": 1,
            "horizontalDistance": 5,
            "verticalDistance": 0,
            "starterCorner": "bottom-left",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 15,
            "startY": 2,
            "speed": 1,
            "horizontalDistance": 0,
            "verticalDistance": 3,
            "starterCorner": "bottom-right",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 27,
            "startY": 1,
            "speed": 2,
            "horizontalDistance": 0,
            "verticalDistance": 4,
            "starterCorner": "bottom-left",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 32,
            "startY": 1,
            "speed": 1,
            "horizontalDistance": 5,
            "verticalDistance": 0,
            "starterCorner": "bottom-left",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 42,
            "startY": 3,
            "speed": 3,
            "horizontalDistance": 5,
            "verticalDistance": 0,
            "starterCorner": "bottom-left",
            "clockwise": true
        }
    ]
}

=== Fredericodgv/FlipNflop/Assets/Resources/Levels/third_level.json
{
    "levelName": "third_level",
    "levelDescription": "implementa obstáculos mace fixos que incentivam a mudança de gravidade e uso do impulso",
    "levelID": "48628629",
    "levelOrder": 30,
    "ffType": "JK",
    "clockCicles": 7,
    "activeClockEdge": "rising",
    "jSignal": "000011 111000 000000 011100 000011 111100 011111 111111",
    "kSignal": "000000 011100 000011 111100 000111 100011 100011 111111",
    "floor": "111111 111111 100111 111111 000111 111111 110001 111111 111111 111111 111",
    "ceiling": " 000001 111111 100001 111111 100001 111111 110001 111111 111111 111111 111",
    "obstacles": [
        {
            "obstacleName": "Mace",
            "startX": 9,
            "startY": 1,
            "speed": 0,
            "horizontalDistance": 0,
            "verticalDistance": 0,
            "starterCorner": "bottom-left",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 20,
            "startY": 4,
            "speed": 0,
            "horizontalDistance": 0,
            "verticalDistance": 0,
            "starterCorner": "top-left",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 32,
            "startY": 1,
            "speed": 0,
            "horizontalDistance": 0,
            "verticalDistance": 0,
            "starterCorner": "bottom-left",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 39,
            "startY": 3,
            "speed": 0,
            "horizontalDistance": 0,
            "verticalDistance": 0,
            "starterCorner": "top-left",
            "clockwise": true
        }
    ]
}

=== Fredericodgv/FlipNflop/Assets/Resources/Levels/fourth_level.json
{
    "levelName": "fourth_level",
    "levelDescription": "implementa obstáculos mace móveis verticais para incentivar escolha prévia da saída",
    "levelID": "82972826",
    "levelOrder": 40,
    "ffType": "JK",
    "clockCicles": 7,
    "activeClockEdge": "rising",
    "jSignal": "000111 110000 111100 011111 111001 110011 110000 111111",
    "kSignal": "000000 001111 110000 111111 001111 100000 011111 001111",
    "floor": "111111 110001 111111 100001 111111 110001 100011 111111 111111 111111 111",
    "ceiling": "111111 111111 100011 111111 110001 100011 111111 111111 111111 111111 111",
    "obstacles": [
        {
            "obstacleName": "Mace",
            "startX": 3,
            "startY": 1,
            "speed": 2,
            "horizontalDistance": 0,
            "verticalDistance": 0,
            "starterCorner": "bottom-left",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 15,
            "startY": 1,
            "speed": 2,
            "horizontalDistance": 0,
            "verticalDistance": 4,
            "starterCorner": "bottom-left",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 26,
            "startY": 3,
            "speed": 2,
            "horizontalDistance": 0,
            "verticalDistance": 0,
            "starterCorner": "top-left",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 38,
            "startY": 1,
            "speed": 2,
            "horizontalDistance": 0,
            "verticalDistance": 4,
            "starterCorner": "bottom-left",
            "clockwise": true
        }
    ]
}

=== Fredericodgv/FlipNflop/Assets/Resources/Levels/fifth_level.json
{
    "levelName": "fifth_level",
    "levelDescription": "Implementa lógica nova de Preset sem sobreposição",
    "levelID": "526828642",
    "levelOrder": 50,
    "ffType": "JK",
    "clockCicles": 8,
    "activeClockEdge": "rising",
    "jSignal": "000111 111100 011100 111000 000011 110001 111000 011000 000111",
    "kSignal": "000111 100011 100001 110000 000111 000111 100111 111100 001111",
    "presetSignal": "111111 111111 111111 110011 111111 111111 111111 100011 111111",
    "asyncActive": "low",
    "ceiling": "111111 100011 111000 011111 111001 110001 111111 111111 111111",
    "floor": "111111 110001 110001 111111 111111 110001 111111 111111 111111",
    "obstacles": [
        {
            "obstacleName": "Mace",
            "startX": 3,
            "startY": 3,
            "speed": 2,
            "horizontalDistance": 0,
            "verticalDistance": 0,
            "starterCorner": "bottom-left",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 14,
            "startY": 4,
            "speed": 2,
            "horizontalDistance": 0,
            "verticalDistance": 0,
            "starterCorner": "bottom-left",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 33,
            "startY": 3,
            "speed": 2,
            "horizontalDistance": 0,
            "verticalDistance": 0,
            "starterCorner": "top-left",
            "clockwise": true
        },
        {
            "obstacleName": "Mace",
            "startX": 46,
            "startY": 2,
            "speed": 1,
            "horizontalDistance": 0,
            "verticalDistance": 0,
            "starterCorner": "top-left",
            "clockwise": true
        }
    ]
}
